version: '3'

volumes:
  production_traefik: {}
  mongodb_production: {}

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: production_wallmart_challenge_frontend
    container_name: frontend_container
    ports:
      - "3000:3000"

  traefik:
    build:
      context: .
      dockerfile: ./compose/traefik/Dockerfile
    image: production_traefik
    depends_on:
      - frontend
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "80:80"
