version: '3'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: production_wallmart_challenge_frontend
    container_name: frontend_container
    ports:
      - "3000:3000"

